
custom:
  accounts:
    DataAgent:
      username: data_agent@wex.gov.uk
    AdminAgent:
      username: admin_agent@wex.gov.uk
    SuperAgent:
      username: super_agent@wex.gov.uk
    SystemUser:
      username: system_user@wex.gov.uk
  
  urls:
    front_office: "http://example.com"
    back_office: "http://example.com"


