# Though not used when we run our CI features these are needed because of the
# way the page objects are loaded.
# They are automatically loaded as the project is read, a consequence of
# cucumber putting everything into global. As such if a reference is made to
# an item in the custom config and its not there the project won't load.
app_host: https://wex-dev.aws-int.defra.cloud
driver: chrome
headless: true
pause: 0
stop_on_error: false
display_failures: true
max_wait_time: 5
print_progress: false
custom:
  accounts:
    DataViewer:
      username: data_viewer@wex.gov.uk
    AdminTeamUser:
      username: admin_team_user@wex.gov.uk
    AdminTeamLeader:
      username: admin_team_lead@wex.gov.uk
    DeveloperUser:
      username: developer@wex.gov.uk
    ServiceManager:
      username: service_manager@wex.gov.uk
    FinanceUser:
      username: finance_user@wex.gov.uk
    PolicyAdviserUser:
      username: policy_adviser@wex.gov.uk
  urls:
    front_office: https://wex-dev.aws-int.defra.cloud
    back_office: https://admin-wex-dev.aws-int.defra.cloud
    notify_link: /email/last-notify-message
